### ISSUE TITLE
How to return a protobuf's map

### ISSUE THREAD

**Issue by ws2003gq** [gorzechowski/flask-restly#16]
my proto：
syntax = "proto3";

message DslEntity {

    map<string,string> headers = 10;
    

    reserved "desc" ;
    

     bytes body  = 2;
}

As you see:
 I want to return a  DslEntity which has a map 

My code :
@resource(name='dslentity')
class DslEntityResource:
    @get('/<int:id>')
    @body(DslEntity_pb2.DslEntity)
    # @body(outgoing=Employee)
    def get_employee(self, id):  
        he=dict(a="av",b="bv")
        return dict(body=b"example",headers={'Name':'Zara'})

The Error below:
[2019-04-19 19:05:44,271] ERROR in __init__: 'google.protobuf.pyext._message.ScalarMapContainer' object has no attribute 'Name'

**Comment by gorzechowski** [comment]
It's an error related with dict to protobuf mapper. Fix is coming ;)

**Comment by gorzechowski** [comment]
`1.0.1` version released, @ws2003gq confirm please if it's ok

**Comment by ws2003gq** [comment]
Good Job. I have checked it.

**Comment by gorzechowski** [comment]
Great, thank you
